Optionize rmarkdown temp directory suffix
rstudio/rmarkdown pull request #2550
Opened 2024-04-03 14:41 UTC by certara-tzweers

We are making this pull request because we have been experiencing an issue with OneDrive deleting html files shortly after knitting them. We have been in email contact with @yihui about updating the knitr_files_dir funtion to aviod this issue (28 Mar 2024, Subject: Rmarkdown: patch for knitr_files_dir).

We have experienced apparently random deletions of html files from OneDrive synced folders shortly after completing the knitting of corresponding Rmd scripts. It appears that this is related to a feature (not bug...) described on this page: 

[Managing the File System - Win32 apps | Microsoft Learn](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fwindows%2Fwin32%2Fshell%2Fmanage%3Fredirectedfrom%3DMSDN%23connected-files&data=05%7C02%7Cthijs.zweers%40certara.com%7C0c51552ea15d4a508ac008dc52ea4203%7C7287abd30220456e98514352bae208c9%7C1%7C0%7C638476413285887341%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=RgGn24MoT69xwfHNl6zGmTJ02FXARdk%2BN6XOskDrPWg%3D&reserved=0)

As such, the issue is a consequence of different components following their designs with an undesirable outcome. A solution to this could be to change the knitr_files_dir function in util.R so the temporary folder for knitr files is not created with a suffix of "_files" but almost anything else, such as "_knitrfiles".

With this update we have made the knitr temp directory suffix configurable via options(rmarkdown.files.suffix = "_knitrfiles") in the knitr_files_dir function.

2024-04-03 14:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rstudio/rmarkdown?pullRequest=2550) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rstudio/rmarkdown?pullRequest=2550) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rstudio/rmarkdown?pullRequest=2550) it.</sub>

2024-04-03 14:45 UTC, yihui requested changes
Thanks!

2024-04-03 14:45 UTC, yihui commented on R/util.R
> +  }
You can just do this:

```suggestion
  suffix <- getOption("rmarkdown.files.suffix", "_files")
```

2024-04-03 14:55 UTC, cderv commented
Thanks a lot. 

Just a little more curious: What exactly happens with this connected files feature ?  
When `*_files` folder is removed then the `.html` file is deleted too. Is that what happens?

Does it happen only on OneDrive folders?  

Thank you !

2024-04-03 15:28 UTC, cderv commented
Thanks a lot. I did not know that and I am really happy to learn this today. This could explain some behavior we have seen for a long time now, and also others on another project using **knitr** and **rmarkdown** (Quarto). 

Thanks again for finding this, and for the PR.

2024-04-03 19:53 UTC, th3nme commented
While researching this issue we also found a post from 2019 describing the same issue with a Windows 10 and Ubuntu machine linked by Google Drive.

https://forum.posit.co/t/html-from-rmd-run-automatically-removed/25469/3

2024-04-04 00:32 UTC, yihui commented
Originally we chose the `_files` suffix precisely because of the association mentioned above (when you copy/move `foo.html`, `foo_files/` is copied/moved automatically). It seems this "intelligent" association does more harm than good in the case of OneDrive.

> Adding the option to change the suffix will give the knitter a way of avoiding this issue but it may be worth considering changing the default from _files to literally almost anything else to avoid the Connected Files default behaviour.

I'm afraid it will be unlikely for us to change the default suffix in the future. It has been used for almost ten years now, and I'm sure that changing the default will create a lot of breaking changes to existing users...

2024-04-04 00:39 UTC, yihui approved these changes
@certara-tzweers Although this is a simple one-liner PR, could you sign the CLA anyway? https://cla-assistant.io/rstudio/rmarkdown?pullRequest=2550

2024-04-09 01:10 UTC, merged